version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=access_doc
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  ws-permission-back:
    image: ws_permission
    container_name: ws-permission-back
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/access_doc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
    - ./documentos:/app/src/main/resources/doc

volumes:
  db:
    driver: local
